name: Release to PyPI

on:
  push:
    tags:        
      - '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  release-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}